### ISSUE TITLE
3D acceleration when virtualizing

### ISSUE THREAD

**Issue by kimsyversen** [TylerLyczak/Unsupported-6900XT-Hackintosh-Fix#15]
I used this guide to get a XTXH working. However when I virtualize, I cannot enable 3D acceleration. If I do this the VM is suddenly terminated. Tested with latest version of Parallels and Ubuntu 22.04. 

Have anyone experience this and know of a fix?

**Comment by TylerLyczak** [comment]
Hello, so the crash happens when you are running Parallels? Does it happen for any other 3D acceleration program?

**Comment by kimsyversen** [comment]
AFAIK it's only Parallels, but I haven't done 'that much' either so I don't know about VMware or Virtualbox for example. I switched from an RX 5800 to 6900 XTXH and that's when I got this issue.
