### ISSUE TITLE
supported TOXIC AMD Radeon™ RX 6900 XT Extreme Edition

### ISSUE THREAD

**Issue by kernelai** [TylerLyczak/Unsupported-6900XT-Hackintosh-Fix#2]
1 gfxutil：
```
0c:00.0 1002:73af /PCI0@0/GPP8@3,1/SWUS@0/SWDS@0/GFX0@0 = PciRoot(0x0)/Pci(0x3,0x1)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)
```
2 SSDT-BRG0.dsl
```
DefinitionBlock ("", "SSDT", 2, "ACDT", "BRG0", 0x00000000)
{
    External (_SB_.PCI0.GPP8.SWUS, DeviceObj)

    Scope (\_SB.PCI0.GPP8.SWUS)
    {
        /*
         * This is a PCI bridge device present on PEGP.
         * Normally seen as pci-bridge in I/O Registry.
         */
        Device (SWDS)
        {
            Name (_ADR, Zero)

            /*
             * This is an actual GPU device present on the bridge.
             * Normally seen as display in I/O Registry.
             */
            Device (GFX0)
            {
                Name (_ADR, Zero)  // _ADR: Address
            }
        }
    }
}

```
3 system:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/7463602/165669783-9596e6f5-8f63-40c4-8bb7-20fad3b14dd5.png">

thanks for your guide and success boot up. this may be an example for others.

by the way, I get path from [IORegistryExplorer](https://github.com/vulgo/IORegistryExplorer) . 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/7463602/165669533-2befbee5-0ac4-4079-a48b-a761d968780a.png"> 
I don't know what that use for. could you explain that to help me understand?

**Comment by TylerLyczak** [comment]
Hmm, that's a weird path. Any kexts you running to change the path?
For the DefinitionBlock, I would change it to `DefinitionBlock ("", "SSDT", 2, "ACDT", "SWDS", 0x00000000)`
Also, I would change the file to `SSDT-SWDS.dsl` since you are not even changing the BRG0 path

**Comment by kernelai** [comment]
I just using a few kext which download from origin officialy.
<img width="344" alt="image" src="https://user-images.githubusercontent.com/7463602/165770400-7812280a-666d-4d0b-a65f-e7ef9903ca41.png">. so don't know did I change it actually.

**Comment by kernelai** [comment]
you are right. I should change file `SSDT-SWDS.dsl`

**Comment by TylerLyczak** [comment]
Issue solved
