### ISSUE TITLE
Ventura

### ISSUE THREAD

**Issue by jamesfawcett** [TylerLyczak/Unsupported-6900XT-Hackintosh-Fix#3]
Hi Tyler, have you got this working yet on OS Ventura? Mine just reboots so I'm debugging to try figure it out.

**Comment by TylerLyczak** [comment]
Haven't tested it out yet. I usually stay away from previews since I use this Hackintosh as a workstation. What errors are you getting?

**Comment by xmannv** [comment]
Confirmed!
This also works on Ventura with 6950 XT also

**Comment by amiltonjr** [comment]
Confirmed, working on MacOS Ventura with RX 6900 XT XH
