### ISSUE TITLE
RX 7900 XT / RX 7900 XTX

### ISSUE THREAD

**Issue by amiltonjr** [TylerLyczak/Unsupported-6900XT-Hackintosh-Fix#4]
Any ideas of MacOS compatibility with those cards?

**Comment by TylerLyczak** [comment]
Honestly not too sure, there has been some rumors with benchmarks but thats about it

**Comment by perez987** [comment]
@amiltonjr 
For now, they are unsupported in macOS. I guess they will remain unsupported in the future.

**Comment by amiltonjr** [comment]
> @amiltonjr
> For now, they are unsupported in macOS. I guess they will remain unsupported in the future.

I'm not sure about that, because when AMD launched the RX 6000 series, there were no MacOS drivers at all, then after a while Big Sur began to support it, because of course Apple started to sell the AMD Radeon Pro W6800X for example. The Mac Pro era isn't yet over.

**Comment by Messa1** [comment]
We will see. I stick for now on a 6950 xt

**Comment by perez987** [comment]
@amiltonjr 
You’re right but now we have Apple Silicon with Intel line discontinued so I’m afraid that there will not be new AMD graphic drivers for macOS. 
But who knows, maybe Apple has different thoughts than me. I will.

**Comment by perez987** [comment]
@amiltonjr 
Please close the issue. Thanks.
