### ISSUE TITLE
GFX0 address in io registry

### ISSUE THREAD

**Issue by 3linedesigns** [TylerLyczak/Unsupported-6900XT-Hackintosh-Fix#5]
Hi I have located my GFX path in gfxutil however in io registry this is the path, I'm using xfx 6900xt merc I believe its XTXH variant

see my two paths below 

gfx util path 
/PC00@0/PEG1@1/PEGP@0/pci-bridge@0/GFX0@0

io registry path
IOService:/AppleACPIPlatformExpert/PC00@0/AppleACPIPCI/PEG1@1/IOPP/PEGP@0/IOPP/pci-bridge@0/IOPP/GFX0@0/AMDRadeonX6000_AmdRadeonControllerNavi21/ATY,RadeonFramebuffer@0/AGPM

Can you help me figure out the correct path to input, the card is currently working in Monterey but at limited capacity

**Comment by TylerLyczak** [comment]
Have you followed the guide? Your path for SSDT-BRG0 should probably be PC00.PEG1.PEGP

**Comment by 3linedesigns** [comment]
Hey, thank u this is exactly what I got as well and made ssdt and device id, everything is working amazing now!

**Comment by TylerLyczak** [comment]
Awesome, glad too hear. Sorry about the late response
