### ISSUE TITLE
Question - what to do if the paths are the same?

### ISSUE THREAD

**Issue by dmcnaugh15** [TylerLyczak/Unsupported-6900XT-Hackintosh-Fix#6]
Hi,

Thanks a lot for this tutorial!

Both my gfxutil and IODevice tree paths match and are the following: 
/PC00@0/PEG1@1/PEGP@0/pci-bridge@0/GFX0@0

So, using your example, lines 12 and 14 appear as follows:

    `External (_SB_.PC00.PEG1.PEGP, DeviceObj)`

    `Scope (\_SB.PC00.PEG1.PEGP)`

Then I tried to replace "BRG0" with "pci-bridge", but MaciASL returned an error and would not allow me to save that.

So, here are my questions:
1. When the paths match, do I need to create the SSDT aml?
2. If so, should I be replacing BRG0 with something else, since "pci-bridge" does not work?
3. Also, should I be replacing BRG0 on both lines 10 and 20?

**Comment by TylerLyczak** [comment]
Hello,

1. Yes, if the GPU doesn't show up, you need the aml. Since the paths match, you can use it how it is without modifying it.
2 and 3. No, keep it BRG0

**Comment by dmcnaugh15** [comment]
The monitor shows up when I go to "About this Mac" (see screenshot), and that is new since updating the config according to your directions.  Before that, it wasn't listed.

The thing I still notice is that under System Settings --> Displays, it says "Unknown Display" (see screenshot) and there is only one resolution (2560 x 1440).  

Is the "Unknown Display" a GPU issue or monitor issue?  Or, maybe a whatevergreen.kext issue?

![About Screenshot](https://user-images.githubusercontent.com/4023680/211315593-49d38a20-511d-4da8-baf5-f40a01633b32.png)
![Display Settings Screenshot](https://user-images.githubusercontent.com/4023680/211315659-fd002969-9246-4748-889a-341da1c9b99b.png)

**Comment by TylerLyczak** [comment]
Im not too sure, but it sounds like more of a mac os issue. I would test if you have GPU acceleration, that would tell you if your GPU is working

**Comment by dmcnaugh15** [comment]
I was able to get this working.  My GPU is a 6600 XT.  So, I had to use a different device ID.  FF730000 was the one that worked for me.  I found it on a website that has all the AMD GPU device IDs.  Thanks for your input.  I couldn't have gotten it going without your instructions here.

**Comment by TylerLyczak** [comment]
Np, glad it's working for you
