### ISSUE TITLE
Confused - very different strings in my setup

### ISSUE THREAD

**Issue by jamescobalt** [TylerLyczak/Unsupported-6900XT-Hackintosh-Fix#7]
From MacOS, I get these:

```
/PC01@0/BR1A@0/SL01@0/pci-bridge@0/display@0 = PciRoot(0x1)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)
IOService:/AppleACPIPlatformExpert/PC01@0/AppleACPIPCI/BR1A@0/IOPP/SL01@0/IOPP/pci-bridge@0/IOPP/display@0
```

```
/PC01@0/BR1A@0/SL01@0/pci-bridge@0/pci1002,ab28@0,1 = PciRoot(0x1)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x1)
IOService:/AppleACPIPlatformExpert/PC01@0/AppleACPIPCI/BR1A@0/IOPP/SL01@0/IOPP/pci-bridge@0/IOPP/pci1002,ab28@0,1
```

From Windows, I get these:
```
ACPI(_SB_)#ACPI(PC01)#ACPI(BR1A)#ACPI(SL01)#PCI(0000)#PCI(0000)
ACPI(_SB_)#ACPI(PC01)#ACPI(BR1A)#ACPI(PEGP)#PCI(0000)#PCI(0000)
```

So that's my first hangup -I get two strings instead of one for my card. I think the 2nd might represent HDMI audio.

I'm not sure what to put in the various lines in the dsl file. I've tried various things, most recently
DefinitionBlock ("", "SSDT", 2, "ACDT", "BR1A", 0x00000000)
   External (_SB_.PC01.BR1A.SL01, DeviceObj)
    Scope (\_SB.PC01.BR1A.SL01)
        Device (BRG0) <- I believe this absorbs "pci-bridge@0"?
            Device (GFX0) <- likewise this absorbs "display@0"?
 

I have the SSDT aml file enabled in config.plist along with the device-id and appropriate boot args. Closest I've gotten is causing the screen to go black on load or instant reboot. 🤔

**Comment by TylerLyczak** [comment]
Hello,
For those paths you got in MacOS, was it from gfxutil or ioreg?
Also, what card are you trying to run?

**Comment by TylerLyczak** [comment]
Also what version of mac os you running?

**Comment by jamescobalt** [comment]
The first lines are gfxutil and the 2nd lines are ioreg, running Ventura 13.0.1. I'm using an ASRock RX 6900 XT OC Formula.

Not sure if this helps: https://imgur.com/a/FaRFgrX

**Comment by TylerLyczak** [comment]
Yeah I'm not sure why your path to your gpu is very different, but it should be PC01.BR1A.SL01

**Comment by jamescobalt** [comment]
Apparently it's because I have an undefined pci-bridge in my ACPI tables and I'm on X299 which is a bit different. I had to define the path in the SSDT first before I could spoof the id, but MacOS crashes on boot. Oh well...

**Comment by irodeanu** [comment]
> Apparently it's because I have an undefined pci-bridge in my ACPI tables and I'm on X299 which is a bit different. I had to define the path in the SSDT first before I could spoof the id, but MacOS crashes on boot. Oh well...

Do you find any solution ?
